publish_to: none

name: illuminate
description: A new Flutter package project.
version: 1.1.0
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.3
  logger: ^1.1.0
  flutter_secure_storage: ^8.0.0
  crypto: ^3.0.2
  dio: ^4.0.6
  go_router: ^6.0.1
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  url_launcher: ^6.1.10
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: