publish_to: none

name: illuminate
description: A new Flutter package project.
version: 1.4.2
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.1.3
  logger: ^1.2.0
  flutter_secure_storage: ^8.0.0
  crypto: ^3.0.2
  dio: ^4.0.6
  go_router: ^6.0.1
  flutter_svg: ^2.0.5
  provider: ^6.0.5
  url_launcher: ^6.1.10
  shimmer: ^2.0.0
  firebase_dynamic_links: ^5.1.1
  googleapis: ^11.0.0
  googleapis_auth: ^1.4.0
  firebase_analytics: ^10.2.0
  firebase_core: ^2.10.0
  uni_links: ^0.5.1
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: