publish_to: none

name: illuminate
description: A flutter package to reduce boilerplate code.
version: 2.0.0
homepage:

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ^3.35.3

dependencies:
  flutter:
    sdk: flutter
  local_auth: ^2.3.0
  logger: ^2.4.0
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.2
  dio: ^5.7.0
  go_router: ^16.2.1
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  url_launcher: ^6.3.0
  shimmer: ^3.0.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  firebase_analytics: ^12.0.1
  firebase_core: ^4.1.0
  app_links: ^6.4.0
  cached_network_image: ^3.2.3
  flutter_markdown: ^0.7.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: